name: Build and Deploy to Docker Hub

on:
  push:

env:
  PROJECT_ID: hanapbh
  GAR_LOCATION: asia-southeast1
  CLIENT_SERVICE: hanapbh-client
  SERVER_SERVICE: hanapbh-server
  REGION: asia-southeast1

jobs:
  build_push_to_docker_hub:
    permissions:
      contents: "write"
      issues: "write"
      pull-requests: "write"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: "actions/setup-node@v4"
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Semantic Release
        run: pnpm install -g semantic-release

      - name: Install Dependencies
        run: pnpm install

      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v3"
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Client Image
        run: |-
          docker build -t "wing09/${{ env.CLIENT_SERVICE }}:latest" ./client \
          --build-arg GOOGLE_CLIENT_ID="${{secrets.GOOGLE_CLIENT_ID}}" \
          --build-arg GOOGLE_CLIENT_SECRET="${{secrets.GOOGLE_CLIENT_SECRET}}" \
          --build-arg GOOGLE_PLACES_API_KEY="${{secrets.GOOGLE_PLACES_API_KEY}}" \
          --build-arg NEXT_PUBLIC_SERVER="${{secrets.NEXT_PUBLIC_SERVER}}" \
          --build-arg SERVER_URL="${{secrets.SERVER_URL}}" \
          --build-arg ClIENT_URL="${{secrets.ClIENT_URL}}" \
          --build-arg NEXTAUTH_SECRET="${{secrets.NEXTAUTH_SECRET}}" \
          --build-arg NEXTAUTH_URL="${{secrets.NEXTAUTH_URL}}"

      - name: Build Server Image
        run: |-
          docker build -t "wing/09${{env.SERVER_SERVICE}}:latest" ./server \
          --build-arg GOOGLE_GEOCODE_API_KEY="${{secrets.GOOGLE_GEOCODE_API_KEY}}" \
          --build-arg GOOGLE_PLACES_API_KEY="${{secrets.GOOGLE_PLACES_API_KEY}}" \
          --build-arg MONGODB_URI="${{secrets.MONGODB_URI}}" \
          --build-arg GMAIL_2F_AUTH_APP_PASS="${{secrets.GMAIL_2F_AUTH_APP_PASS}}"

      - name: run semantic release
        run: pnpm install && npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
