name: Build and Deploy to Docker Hub

on:
  release:
    types:
      - published

env:
  PROJECT_ID: hanapbh
  GAR_LOCATION: asia-southeast1
  CLIENT_SERVICE: hanapbh-client
  SERVER_SERVICE: hanapbh-server
  REGION: asia-southeast1

jobs:
  build_push_to_docker_hub_and_cloud_run:
    permissions:
      contents: "write"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{secrets.GA_PAT}}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            "${{ env.GAR_LOCATION }}/${{ env.CLIENT_SERVICE }}"
            "${{ env.GAR_LOCATION }}/${{ env.SERVER_SERVICE }}"
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Determine Tag
        id: tag
        run: |
          # Determine the tag based on the repository or branch
          echo "REPO_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v3"
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PAT}}

      - name: Build and Push Client Image
        id: build-push-client-image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            GOOGLE_CLIENT_ID="${{secrets.GOOGLE_CLIENT_ID}}"
            GOOGLE_CLIENT_SECRET="${{secrets.GOOGLE_CLIENT_SECRET}}"
            NEXT_PUBLIC_GOOGLE_PLACES_API_KEY="${{secrets.NEXT_PUBLIC_GOOGLE_PLACES_API_KEY}}"
            NEXT_PUBLIC_SERVER="${{secrets.NEXT_PUBLIC_SERVER}}"
            SERVER_URL="${{secrets.SERVER_URL}}"
            CLIENT_URL="${{secrets.CLIENT_URL}}"
            NEXTAUTH_SECRET="${{secrets.NEXTAUTH_SECRET}}"
            NEXTAUTH_URL="${{secrets.NEXTAUTH_URL}}"
            UPLOADTHING_SECRET="${{secrets.UPLOADTHING_SECRET}}"
            NEXT_PUBLIC_GOOGLE_MAPS_API_KEY="${{secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}}"
            context: ./client
          push: true
          tags: "wing09/${{ env.CLIENT_SERVICE }}:${{ env.REPO_TAG }}"

      - name: Build and Push Server Image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            GOOGLE_GEOCODE_API_KEY="${{secrets.GOOGLE_GEOCODE_API_KEY}}"
            GOOGLE_PLACES_API_KEY="${{secrets.GOOGLE_PLACES_API_KEY}}"
            MONGODB_URI="${{secrets.MONGODB_URI}}"
            GMAIL_2F_AUTH_APP_PASS="${{secrets.GMAIL_2F_AUTH_APP_PASS}}"
          context: ./server
          push: true
          tags: "wing09/${{env.SERVER_SERVICE}}:${{ env.REPO_TAG }}"
