name: Build and Deploy to Docker Hub

on:
  release:
    types:
      - published

env:
  PROJECT_ID: hanapbh
  GAR_LOCATION: asia-southeast1
  CLIENT_SERVICE: hanapbh-client
  SERVER_SERVICE: hanapbh-server
  REGION: asia-southeast1

jobs:
  build_push_to_docker_hub_and_cloud_run:
    permissions:
      contents: "write"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{secrets.GA_PAT}}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            "${{ env.GAR_LOCATION }}/${{ env.CLIENT_SERVICE }}"
            "${{ env.GAR_LOCATION }}/${{ env.SERVER_SERVICE }}"
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Determine Tag
        id: tag
        run: |
          # Determine the tag based on the repository or branch
          echo "REPO_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v3"
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PAT}}

      - name: Build and Push Client Image
        id: build-push-client-image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            GOOGLE_CLIENT_ID="${{secrets.GOOGLE_CLIENT_ID}}"
            GOOGLE_CLIENT_SECRET="${{secrets.GOOGLE_CLIENT_SECRET}}"
            GOOGLE_PLACES_API_KEY="${{secrets.GOOGLE_PLACES_API_KEY}}"
            NEXT_PUBLIC_SERVER="${{secrets.NEXT_PUBLIC_SERVER}}"
            SERVER_URL="${{secrets.SERVER_URL}}"
            CLIENT_URL="${{secrets.CLIENT_URL}}"
            NEXTAUTH_SECRET="${{secrets.NEXTAUTH_SECRET}}"
            NEXTAUTH_URL="${{secrets.NEXTAUTH_URL}}"
          context: ./client
          push: true
          tags: "wing09/${{ env.CLIENT_SERVICE }}:${{ env.REPO_TAG }}"

      - name: Build Server Image
        run: |-
          docker build -t "wing09/${{env.SERVER_SERVICE}}:${{ env.REPO_TAG }}" ./server \
          --build-arg GOOGLE_GEOCODE_API_KEY="${{secrets.GOOGLE_GEOCODE_API_KEY}}" \
          --build-arg GOOGLE_PLACES_API_KEY="${{secrets.GOOGLE_PLACES_API_KEY}}" \
          --build-arg MONGODB_URI="${{secrets.MONGODB_URI}}" \
          --build-arg GMAIL_2F_AUTH_APP_PASS="${{secrets.GMAIL_2F_AUTH_APP_PASS}}"

      - name: Push Server Image to Docker Hub
        run: docker push "wing09/${{env.SERVER_SERVICE}}:${{ env.REPO_TAG }}"

      - name: ReTag Server Image
        run: docker tag "wing09/${{env.SERVER_SERVICE}}:${{ env.REPO_TAG }}" "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVER_SERVICE }}/${{ env.SERVER_SERVICE }}:${{ env.REPO_TAG }}"


      - name: Push Server Image to Artifact Registry
        run: docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVER_SERVICE }}/${{ env.SERVER_SERVICE }}:${{ env.REPO_TAG }}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVER_SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVER_SERVICE }}/${{ env.SERVER_SERVICE }}:${{ env.REPO_TAG }}

      - name: Save new Docker Image version
        run: |-
          sed -i 's|wing09/${{ env.CLIENT_SERVICE }}: .*|wing09/${{ env.CLIENT_SERVICE }}:${{ env.REPO_TAG }}|' README.md
          sed -i 's|wing09/${{ env.SERVER_SERVICE }}: .*|wing09/${{ env.SERVER_SERVICE }}:${{ env.REPO_TAG }}|' README.md

          sed -i 's|wing09/${{ env.CLIENT_SERVICE }}: .*|wing09/${{ env.CLIENT_SERVICE }}:${{ env.REPO_TAG }}|' docker-compose.yml
          sed -i 's|wing09/${{ env.SERVER_SERVICE }}: .*|wing09/${{ env.SERVER_SERVICE }}:${{ env.REPO_TAG }}|' docker-compose.yml

          git config --global user.name 'Wilfreno'
          git config --global user.email 'w.gayongan@gmail.com'

          git add README.md docker-compose.yml
          git commit -m 'Update README.md with latest Docker image tags'
          git push origin HEAD:main --force

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
