name: Create Release Version

on:
  push:

jobs:
  release:
    permissions:
      contents: "write"
      issues: "write"
      pull-requests: "write"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Node
        uses: "actions/setup-node@v4"
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Semantic Release
        run: pnpm install -g semantic-release

      - name: Install Dependencies
        run: pnpm install

      - name: run semantic release
        id: semantic_release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}